#ifndef PBGZ_MANAGER_H_
#define PBGZ_MANAGER_H_

#include "singleton.h"
#include "info.h"
#include "err_code.h"
#include "file_op.h"
#include "memory.h"
#include <memory>
#include <vector>
#include <string>
#include <chrono>
#include "analy_type.h"

/**
 * @brief Constants for determining compression strategy
 */
#define GENE3_MAX_BASE (10485760) // Process as binary compression if larger than 10MB
#define GENE2_MAX_BASE (2048)     // Process as 3rd-gen data if larger than 2KB

/**
 * @brief Check condition and exit with error message if not satisfied
 * 
 * @param condition Boolean expression to check
 * @param exit_code Exit code to use if condition fails
 * @param ... Format string and arguments for error message
 */
#define check(condition, exit_code, ...) \
    do { \
        if (!(condition)) { \
            fprintf(stderr, "error: "); \
            fprintf(stderr, __VA_ARGS__); \
            fprintf(stderr, "\n"); \
            manage::instance().exit(exit_code); \
        } \
    } while (0)
    
/**
 * @brief Check condition and return with warning if not satisfied
 * 
 * @param cond Boolean expression to check
 * @param code Return code to use if condition fails
 * @param ... Format string and arguments for warning message
 */
#define check_warning(cond, code, ...) \
    do { \
        if (!(cond)) { \
            fprintf(stderr, "warning: "); \
            fprintf(stderr, __VA_ARGS__); \
            fprintf(stderr, "\n"); \
            return code; \
        } \
    } while (0)

/**
 * @brief Check condition and exit with debug info if not satisfied
 * 
 * @param cond Boolean expression to check
 * @param code Exit code to use if condition fails
 * @param ... Format string and arguments for error message
 */
#define check_exit_debug(cond, code, ...) \
    do { \
        if (!(cond)) { \
            fprintf(stderr, \
                    "%s:%d check_exit_debug(%s) failed: ", \
                    __FILE__, \
                    __LINE__, \
                    #cond); \
            fprintf(stderr, __VA_ARGS__); \
            fprintf(stderr, "\n"); \
            manage::instance().exit(code); \
        } \
    } while (0)

/**
 * @brief Check condition and exit if not satisfied
 * 
 * @param cond Boolean expression to check
 * @param code Exit code to use if condition fails
 * @param ... Format string and arguments for error message
 */
#define check_exit(cond, code, ...) \
    do { \
        if (!(cond)) { \
            fprintf(stderr, "\nerror: "); \
            fprintf(stderr, __VA_ARGS__); \
            fprintf(stderr, "\n"); \
            manage::instance().exit(code); \
        } \
    } while (0)

/**
 * @brief High-precision timer for performance measurements
 * 
 * This timer can be safely used across multiple threads.
 */
class timer {
public:
    /**
     * @brief Construct a new Timer object
     * 
     * @param autostart If true, timer starts upon construction
     */
    explicit timer(bool autostart = false) {
        if (autostart) {
            reset();
        }
    }

    /**
     * @brief Reset the timer to current time
     */
    void reset() {
        _start = std::chrono::high_resolution_clock::now();
    }

    /**
     * @brief Get elapsed milliseconds since reset
     * 
     * @return uint32_t Elapsed time in milliseconds
     */
    uint32_t elapsed() const {
        auto now = std::chrono::high_resolution_clock::now();
        return static_cast<uint32_t>(
            std::chrono::duration_cast<std::chrono::milliseconds>(now - _start).count()
        );
    }

private:
    std::chrono::time_point<std::chrono::high_resolution_clock> _start;
};

/**
 * @brief Find the closest power of 2 to a number
 * 
 * @param n Input integer
 * @return int32_t Closest power of 2
 */
int32_t powerof2_proximal(int32_t n);

/**
 * @brief Main manager class for the PBGZ compression engine
 */
class manager {
public:
    /**
     * @brief Construct a new Manager object
     */
    manager();

    /**
     * @brief Destroy the Manager object
     */
    virtual ~manager();

    /**
     * @brief Set compression information
     * 
     * @param val Configuration info for compression
     */
    void set_zipinfo(const info &val);

    /**
     * @brief Get current compression information
     * 
     * @return const info& Current compression settings
     */
    const info &get_zipinfo();

    /**
     * @brief Exit the program with specified error code and message
     * 
     * @param code Exit code
     * @param reason Error message
     * @param err Error flag (1 for error, 0 for normal exit)
     */
    void exit(int code, const std::string &reason = "", int err = 1);

private:
    /** Compression settings */
    info zipinfo;

    /** List of output files generated by the current task */
    std::vector<std::pair<std::string, bool>> outfiles;
};

/** Global singleton access to manager */
typedef singleton<manager> manage;

#endif // PBGZ_MANAGER_H_